### PR TITLE
Bump version to v2.19.2

### PR DESCRIPTION
**Pull request by DrewZhang13**
*Issue #, if available:*

*Description of changes:*
Bump version to v2.19.2

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by DrewZhang13** [comment]
Do not merge this until kinesis version bump finish.
https://github.com/aws/amazon-kinesis-streams-for-fluent-bit/pull/167

**Comment by DrewZhang13** [comment]
This is my local fork with SSL patch: https://github.com/DrewZhang13/fluent-bit/commits/1.8.7-SSL-patch
This is based on fluent bit 1.8.7 version and picked this commit: 
https://github.com/fluent/fluent-bit/pull/4100/commits/8d1cfeb5ba830b360fe6e1228190ed900842a3ea

**Review by zhonghui12 — COMMENTED** [review]
We need to update the version of kinesis streams in Dockerfile.plugins as well

**Comment by zhonghui12** [comment]
Close this one as we will release 2.20.0 instead

**Pull request closed without merging**
