### PR TITLE
debugging: add tail multiple and firehose/kinesis partial success sec…

### PR DESCRIPTION
**Pull request by PettitWesley**
…tions

Signed-off-by: Wesley Pettit <wppttt@amazon.com>

*Issue #, if available:*

*Description of changes:*

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Review by matthewfala — APPROVED** [review]
This looks great!
We should be able to solve the log duplication problem here if we wanted to:
https://docs.aws.amazon.com/kinesis/latest/APIReference/API_PutRecords.html

We would just make a hash map with a key based on the chunk's memory address. The value would be a boolean array of true and false flags based on each records success status. Always check the hash map before sending logs and avoid sending duplicates.

**Comment by PettitWesley** [comment]
@matthewfala agreed- do you want to open an upstream issue for that, since it would be an upstream change

**Comment by matthewfala** [comment]
We do have to consider clean up. We could probably just keep track of the retries and if we're on the last attempt, then get rid of the hash entry.

**Comment by matthewfala** [comment]
Sure!

**Comment by matthewfala** [comment]
https://github.com/fluent/fluent-bit/issues/6369

**Pull request merged**
