### PR TITLE
re bump to version 2.19.0

### PR DESCRIPTION
**Pull request by DrewZhang13**
Signed-off-by: Drew Zhang <zhayuzhu@amazon.com>

*Issue #, if available:*

*Description of changes:*

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by DrewZhang13** [comment]
Do not merge before 2.17 release process finish

**Review by hossain-rayhan — COMMENTED** [review]
Maybe you can mark the PR as draft for now and publish it again when the v2.17.0 finishes.

**Comment by DrewZhang13** [comment]
> Maybe you can mark the PR as draft for now and publish it again when the v2.17.0 finishes.

How could I mark a PR as draft?

**Review by PettitWesley — APPROVED** [review]

**Comment by DrewZhang13** [comment]
The deployment is finished so should be good to review and merge now

**Review by hossain-rayhan — APPROVED** [review]

**Pull request merged**
